# harl/models/value_function_models/qmix_mixer.py

"""QMIX mixing network.

This module implements the monotonic mixing network used by QMIX:

    Q_tot = f_mix(Q_1, ..., Q_n, s)

where the mixing weights are generated by hypernetworks conditioned on the
centralized state and constrained to be non-negative.
"""

import numpy as np
import torch
import torch.nn as nn

from harl.utils.envs_tools import get_shape_from_obs_space
from harl.utils.models_tools import init, get_init_method

def flatten_share_obs_space(share_obs_space):
    """
    将 share_obs_space 转成单个整数 state_dim，
    兼容 SMAC list 风格和 GRF Box 风格。
    """
    # 如果是 list/tuple，取第一个元素作为代表
    if isinstance(share_obs_space, (list, tuple, np.ndarray)):
        first = share_obs_space[0]

        def recursive_flatten(x):
            if isinstance(x, int):
                return x
            elif isinstance(x, (list, tuple, np.ndarray)):
                total = 0
                for i in x:
                    total += recursive_flatten(i)
                return total
            elif hasattr(x, "shape"):  # Box
                return int(np.prod(x.shape))
            else:
                raise ValueError(f"Unexpected type in share_obs_space: {type(x)}")

        return recursive_flatten(first)

    # 如果是 Box 或单整数
    if hasattr(share_obs_space, "shape"):
        return int(np.prod(share_obs_space.shape))
    if isinstance(share_obs_space, int):
        return share_obs_space

    raise ValueError(f"Unsupported share_obs_space type: {type(share_obs_space)}")

class QMixer(nn.Module):
    """QMIX monotonic mixing network."""

    def __init__(self, args, share_obs_space, device=torch.device("cpu")):
        super(QMixer, self).__init__()

        self.num_agents = args["num_agents"]
        self.embed_dim = args.get("mixer_embed_dim", 32)
        self.hypernet_embed = args.get("hypernet_embed", 64)
        self.initialization_method = args.get("initialization_method", "orthogonal_")
        self.tpdv = dict(dtype=torch.float32, device=device)

        # -------------------------
        # 核心修改：flatten share_obs_space
        # -------------------------
        self.state_dim = flatten_share_obs_space(share_obs_space)

        init_method = get_init_method(self.initialization_method)

        def init_(m):
            return init(m, init_method, lambda x: nn.init.constant_(x, 0))

        self.hyper_w_1 = nn.Sequential(
            init_(nn.Linear(self.state_dim, self.hypernet_embed)),
            nn.ReLU(),
            init_(nn.Linear(self.hypernet_embed, self.num_agents * self.embed_dim)),
        )

        self.hyper_w_final = nn.Sequential(
            init_(nn.Linear(self.state_dim, self.hypernet_embed)),
            nn.ReLU(),
            init_(nn.Linear(self.hypernet_embed, self.embed_dim)),
        )

        self.hyper_b_1 = init_(nn.Linear(self.state_dim, self.embed_dim))

        self.V = nn.Sequential(
            init_(nn.Linear(self.state_dim, self.embed_dim)),
            nn.ReLU(),
            init_(nn.Linear(self.embed_dim, 1)),
        )

        self.to(device)

    def forward(self, agent_qs, states):
        """Mix individual agent Q-values into Q_tot.

        Args:
            agent_qs: Tensor with shape [batch, n_agents] or
                [batch, time, n_agents].
            states: Tensor with shape [batch, state_dim] or
                [batch, time, state_dim].

        Returns:
            q_tot: Tensor with shape [batch, 1] or [batch, time, 1].
        """
        agent_qs = agent_qs.to(**self.tpdv)
        states = states.to(**self.tpdv)

        original_shape = agent_qs.shape[:-1]

        # Flatten leading dimensions.
        agent_qs = agent_qs.reshape(-1, self.num_agents)
        states = states.reshape(-1, self.state_dim)

        batch_size = agent_qs.shape[0]

        # First layer.
        w1 = torch.abs(self.hyper_w_1(states))
        w1 = w1.view(batch_size, self.num_agents, self.embed_dim)

        b1 = self.hyper_b_1(states)
        b1 = b1.view(batch_size, 1, self.embed_dim)

        hidden = torch.bmm(agent_qs.view(batch_size, 1, self.num_agents), w1) + b1
        hidden = torch.relu(hidden)

        # Final layer.
        w_final = torch.abs(self.hyper_w_final(states))
        w_final = w_final.view(batch_size, self.embed_dim, 1)

        v = self.V(states).view(batch_size, 1, 1)

        q_tot = torch.bmm(hidden, w_final) + v
        q_tot = q_tot.view(*original_shape, 1)

        return q_tot